*** empty log message ***

diff --git a/QNX4/libsrc/flinit b/QNX4/libsrc/flinit
--- a/QNX4/libsrc/flinit
+++ b/QNX4/libsrc/flinit
@@ -1,31 +1,34 @@
-#! /bin/sh
+#! /usr/bin/env ENV="" /bin/sh
+# This script should get a little more error checking before being
+# made setuid. It has been cleared for use by root, blocking obvious
+# security holes.
 
 #__USAGE
 #%C	<device>
 #	initialise a floppy for QNX raw data
 
 case $# in
-	0) exec use $0;;
+  0) exec use $0;;
 esac
 
 for dev
 do
-	echo formatting $dev
-	echo insert floppy in $dev
-	if fdformat -ap $dev
+  echo formatting $dev
+  echo insert floppy in $dev
+  if /bin/fdformat -ap $dev
+  then
+	/bin/umount $dev
+	echo block checking $dev
+	if /bin/dcheck -V $dev
 	then
-		sleep 10
-		echo block checking $dev
-		if dcheck -V $dev
-		then
-			echo "Disk suitable for archiving"
-			exit 0
-		else
-			echo "Disk NOT suitable for archiving: bad blocks"
-			exit 1
-		fi
+	  echo "Disk suitable for archiving"
+	  exit 0
 	else
-		echo "Disk NOT suitable for archiving: error in fdformat"
-		exit 1
+	  echo "Disk NOT suitable for archiving: bad blocks"
+	  exit 1
 	fi
+  else
+	echo "Disk NOT suitable for archiving: error in fdformat"
+	exit 1
+  fi
 done
diff --git a/QNX4/libsrc/netinstall b/QNX4/libsrc/netinstall
--- a/QNX4/libsrc/netinstall
+++ b/QNX4/libsrc/netinstall
@@ -17,6 +17,9 @@
 
 # History:
 #  $Log$
+# Revision 1.10  1995/10/17  17:44:41  nort
+# Many changes to ease upgrades
+#
 # Revision 1.9  1995/04/24  21:27:35  nort
 # Upped "Large" boot partition from 2m to 4m
 # Load TZ.init before initial rtc
@@ -28,7 +31,7 @@
 #
 typeset UPGRADE LIBS_TOO FDISK TGTNODE DISKDRV DISKPARM LOCAL
 typeset RUNDOS
-typeset DosF DosQuote Net NetA NetN NetW Tinit Mouse Int10
+typeset DosF DosQuote NetA NetN NetW Tinit Mouse Int10
 typeset Dev DevCon DevSer DevPar FsysFl
 typeset opts excl n j option isFlt notFlt
 UPGRADE=no
@@ -99,12 +102,10 @@ function query_config {
   typeset prog
   echo Querying Current Configuration of $1 >&2
   prog=`sin -h -n $TGTNODE -P $1 format a 2>/dev/null`
-  if [ -n "$prog" ]; then
-	echo "Current Configuration is: $prog:" >&2
-  else
+  if [ -z "$prog" ]; then
 	if [ -n "$2" ]; then
 	  prog="# $1$2"
-	  echo "Configuration not found, using default: $prog" >&2
+	  # echo "Configuration not found, using default: $prog" >&2
 	else
 	  prog=""
 	fi
@@ -149,7 +150,7 @@ esac
 Dev=`sin -n $TGTNODE -P Dev -h format a | grep "Dev "`
 DevCon=`query_config Dev.ansi " -n 4"`
 DevSer=`query_config Dev.ser " "`
-DevPar=`query_config Dev.apr " "`
+DevPar=`query_config Dev.par " "`
 FsysFl=`query_config Fsys.floppy " "`
 DosF=`query_config Dosfsys`
 if [ -n "$DosF" ]; then
@@ -167,13 +168,13 @@ else
 fi
 Int10=`query_config int10 " "`
 
-Net=`sin -n $TGTNODE -P Net -h format a | grep "Net "`
+# Net=`sin -n $TGTNODE -P Net -h format a | grep "Net "`
 NetA=`query_config Net.arcnet " -s "`
 NetN=`query_config Net.ether1000 " -l2 -n2 -6 -s16 "`
 NetW=`query_config Net.ether8003 " -l2 -n2 "`
 
 if [ -z "$isFlt" ]; then
-  Tinit='tinit -c "/bin/login -f flight" -t /dev/con1'
+  Tinit='tinit -c "/bin/login -f flight" -t /dev/con1 '
 else
   Tinit=`query_config tinit " -T /dev/con* -t /dev/con1 "`
 fi
@@ -201,7 +202,7 @@ fi
 #----------------------------------------------------------------
 sin -n$TGTNODE info >/dev/null || exit 1
 
-export TZ=est05edt04,M4.1.0/2,M10.5.0/2
+# export TZ=est05edt04,M4.1.0/2,M10.5.0/2
 sin -n $TGTNODE -P /bin/date 2>/dev/null | grep /bin/date >/dev/null || {
   echo Starting clock
   on -n $TGTNODE -t //$TGTNODE/dev/con1 clock -b cyan -f bwhite "+%D %r"
@@ -306,18 +307,18 @@ ${isFlt}export TZ=utc00
 ${notFlt}export TZ=est05edt04,M4.1.0/2,M10.5.0/2
 ${notFlt}[ -x /etc/config/TZ.init ] && . /etc/config/TZ.init
 rtc$LOCAL hw
-${Dev}&
-${DevCon}&
-${DevSer}&
-${DevPar}&
+${Dev} &
+${DevCon} &
+${DevSer} &
+${DevPar} &
 
 reopen //0/dev/con1
 set -- \`fullpath \$0\`
 echo Booting Node \$NODE from disk \(\$3\)
 
 emu87 &
-${FsysFl}&
-${DosF}&
+${FsysFl} &
+${DosF} &
 ${DosQuote}echo Waiting for Dosfsys to initialize...
 ${DosQuote}while [ ! -d /dos/c ]; do sleep 2; done
 ${DosQuote}echo Continuing
@@ -325,11 +326,11 @@ ${DosQuote}echo Continuing
 #----------------------------------------------------------------
 # Start up the QNX Network
 #----------------------------------------------------------------
-${Net}&
+Net &
 netmap -f
-${NetA}&
-${NetN}&
-${NetW}&
+${NetA} &
+${NetN} &
+${NetW} &
 
 #----------------------------------------------------------------
 # Start our nameloc or wait for the server's
diff --git a/QNX4/libsrc/update_host b/QNX4/libsrc/update_host
--- a/QNX4/libsrc/update_host
+++ b/QNX4/libsrc/update_host
@@ -5,11 +5,15 @@
 typeset debug="no"
 
 ################################################################
+# (This usage info is basically obsolete. update_host
+# does not copy files, but writes them into archives.)
+# Latest version places the archive, message_file, manifest.$tgt
+# and setup in the current directory.
+#
 # Body of the procedure:
 # %C	<srcnode> <tgtnode>
 #
 # Reads command lines from stdin
-# Writes non-trivial actions to stdout
 # Writes error codes to stderr
 # Commands:
 #  /[+] <directory> <perms> <owner>
@@ -21,39 +25,33 @@ typeset debug="no"
 #    newer, preserving permissions and verbose:  cp -fpvn
 #    For thorough update, might use cp -fpv. -f forces
 #    symbolic links to be removed before a file is copied.
-#
-#    Files which should be symbolically linked to the source
-#    file take the special flag 'S'. In this case the soft
-#    link is performed if the target file doesn't exist or
-#    is not the same as the source file.
-#
-#    <filename> may specify a directory only in the case
-#    of a symbolic link to the source directory.
-#
-#    Note: for OS updates, modification of certain files
-#    should trigger /etc/make_links. Namely anything on
-#    the left side of ln -f should trigger make_links and
-#    anything on the right side should be excluded from the
-#    list. Files followed by an M are so designated.
 ################################################################
 typeset src=$1 tgt=$2
-typeset tgtdir srcdir catcode fname flags owner os_links="no" severity=0
-typeset timefile file paxfile
+typeset tgtdir srcdir catcode fname flags owner severity=0
+typeset timefile file paxfile listfile
 
-if [ -z "$src" -o -z "$tgt" ]; then
-  echo "update_node: Missing source ($src) or target ($tgt) definition" >&2
-  exit 1
-fi
-if [ ! -d //$src/ ]; then
-  echo Source node //$src/ unreachable >&2
-  exit 1
+if [ -z "$tgt" -a -n "$src" ]; then
+  tgt="$src"
+  src=""
+else
+  if [ -z "$src" -o -z "$tgt" ]; then
+	echo "update_node: Missing source ($src) or target ($tgt) definition" >&2
+	exit 1
+  fi
+  if [ ! -d //$src/ ]; then
+	echo Source node //$src/ unreachable >&2
+	exit 1
+  fi
 fi
 tgt=`echo $tgt | tr [A-Z] [a-z]`
-timefile=//$src/etc/config/update.$tgt
 paxfile=$tgt.pax
-[ -f $timefile ] && timed=yes
+listfile=manifest.$tgt
 
-cat >message_file <<-THE_END
+if [ -n "$src" ]; then
+  timefile=//$src/etc/config/update.$tgt
+  [ -f $timefile ] && timed="-newer $timefile"
+
+  cat >message_file <<-THE_END
 
 
 
@@ -70,55 +68,63 @@ cat >message_file <<-THE_END
 
 
 THE_END
-message_file=yes
+  message_file=yes
 
-while read catcode fname flags owner; do
-  if [ -n "$message_file" ]; then
-	echo "message_file"
-	unset message_file
-  fi
-  case $catcode in
-	#*) :;;
-	\/*)
-	  echo //$src$fname
-	  tgtdir=$fname/; srcdir=//$src$fname/;;
-	*)
-	  case $flags in
-		*P*)
-		  ;;
-		*[HSs]*)
-		  # linked files (not supported?)
-		  echo Error: $srcdir$fname linked via $flags in host update >&2
-		  severity=1;;
-		*)
-		  # we ignore the soft link with regular files
-		  # just output the file if it meets the criteria?
-		  for file in $srcdir$fname; do
-			if [ -d "$file" ]; then
-			  if [ -z "$timed" ]; then
-				find $file -type f
-			  else
-				find $file -type f -newer $timefile
+  while read catcode fname flags owner; do
+	if [ -n "$message_file" ]; then
+	  echo "message_file"
+	  unset message_file
+	fi
+	case $catcode in
+	  #*) :;;
+	  \/*)
+		echo //$src$fname
+		tgtdir=$fname/; srcdir=//$src$fname/;;
+	  *)
+		case $flags in
+		  *P*)
+			;;
+		  *[S]*)
+			# linked files (not supported?)
+			echo Error: $srcdir$fname linked via $flags in host update >&2
+			severity=1;;
+		  *[Hs]*)
+			# These ones should be handled by pax OK
+			echo $srcdir$fname;;
+		  *)
+			# we ignore the soft link with regular files
+			# just output the file if it meets the criteria?
+			for file in $srcdir$fname; do
+			  if [ -d "$file" ]; then
+				find $file -type f $timed
+				find $file -type f $timed -perm -u+rws -print >>setup
+			  elif [ -f "$file" ]; then
+				if [ -z "$timed" -o "$file" -nt $timefile ]; then
+				  echo $file
+				  find $file -type f -perm -u+rws -print >>setup
+				fi
 			  fi
-			elif [ -f "$file" ]; then
-			  [ -z "$timed" -o "$file" -nt $timefile ] &&
-				echo $file
-			fi
-		  done;;
-	  esac;;
-  esac
-done >manifest.$tgt
+			done;;
+		esac;;
+	esac
+  done >$listfile
+  if [ -s setup ]; then
+	echo "setup" >>$listfile
+	awk '{sub("^//[0-9]*",""); print "/bin/chmod o-rw,u+s " $1}' setup >setup.tmp
+	mv -f setup.tmp setup
+	chmod a+x setup
+  else
+	rm -f setup
+  fi
 
-pax -wv -s,//$src,, -s,message_file,/dev/tty, < manifest.$tgt > $paxfile
+  touch $timefile
 
-touch $timefile
+elif [ ! -f $listfile ]
+  echo "Listing file $listfile not found" >&2
+  exit 1
+fi
 
-rm message_file
-
-pax -v <$paxfile | grep "^-rws" | awk '{print "/bin/chmod o-rw,u+s " $NF}' >setup
-chmod a+x setup
-pax -a -f $paxfile setup
-rm setup
+pax -wv -s,//$src,, -s,message_file,/dev/tty, < $listfile > $paxfile
 
 freeze -f $paxfile
 
