Updated standard maintenance targets.

diff --git a/QNX4/includes/Makefile b/QNX4/includes/Makefile
--- a/QNX4/includes/Makefile
+++ b/QNX4/includes/Makefile
@@ -1,5 +1,8 @@
 # makefile for /usr/local/include
 # $Log$
+# Revision 1.2  1992/05/19  21:13:51  nort
+# Got rid of "tmc"
+#
 # Revision 1.1  1992/05/19  18:30:10  nort
 # Initial revision
 #
@@ -11,6 +14,9 @@ DOC=
 OBJ=
 INTERMED=
 TEMPORARY=
+MNC=linc
+SAVE=$(SRC) $(TOOL) $(DOC)
+PURGE=$(OBJ) $(INTERMED) $(TEMPORARY)
 
 all : archive
 
@@ -23,35 +29,63 @@ all : archive
 #	make backup archive
 #	make update
 #	make archlist
+# This set of commands should be entirely generic given the
+# definition of the following macros:
+#   MNC the name of the backup directory. This should be
+#       unique system-wide, since it will probably go into
+#       the same directory with all the other backup directories
+#   SUBDIRS list of subdirectories that should be grouped together
+#       with this one for maintenance purposes.
+#   INCLUDED list of files from /usr/local/include which are
+#       used in this directory. This will be copied together
+#       with other source files into an "included" subdirectory
+#       when the backup target is invoked.
+#	SAVE list of files which are to be saved during backup
+#	PURGE list of files which are to be deleted during cleanup
+#	SAVE and PURGE should list all files in the directory.
+#		make unlisted (or exchange) will alert you to any
+#		files not listed in one or the other category.
 #-----------------------------------------------------------------
 # BACKUPDIR is where duplicate copies of source files are kept
-MNC=linc
-BACKUPDIR=/tmp/$(MNC)
-SAVE=$(SRC) $(TOOL) $(DOC)
-PURGE=$(OBJ) $(INTERMED) $(TEMPORARY)
+BACKUPROOT=$(TMPDIR)
+BACKUPDIR=$(BACKUPROOT)/$(MNC)
+ULRT=$(TMPDIR)/$(MNC)
+RECURSE=if test -n "$(SUBDIRS)"; then\
+	  for i in $(SUBDIRS); do\
+	    if (cd $$i; $(MAKE) $(MAKEFLAGS) BACKUPROOT=$(BACKUPDIR) $@);\
+		then :;\
+		else exit 1;\
+		fi;\
+	  done;\
+	else :;\
+	fi;
+
 # make clean reduces to source code only
-# Add commands to recurse as necessary:
-#	cd regress; $(MAKE) $(MAKEFLAGS) clean
 clean :
+	@$(RECURSE)
 	rm $(PURGE)
 	rm -r $(BACKUPDIR)
 
 # make exchange exchanges newer versions of source with a backup directory.
 # make backup copies the RCS files also. make backup archive should therefore
 # backup the current source AND the RCS files.
-# add commands to recurse through subdirectories as necessary:
-#	cd regress; $(MAKE) $(MAKEFLAGS) exchange
 exchange :
 	@cp -civn $(SAVE) $(BACKUPDIR); :
 	@cd $(BACKUPDIR); find . -level 1 -a -type f | xargs -i cp -civn {} $(PWD); :
+	@$(RECURSE)
 backup : exchange
-	if test -d $(BACKUPDIR)/RCS; then : ; else mkdir $(BACKUPDIR)/RCS; fi; :
-	cp RCS/* $(BACKUPDIR)/RCS
+	@if test -n "$(INCLUDED)"; then\
+	  cd /usr/local/include; cp -cvn $(INCLUDED) $(BACKUPDIR)/included;\
+	fi; :
+	@if test -d RCS; then\
+	  cp -cvn RCS/* $(BACKUPDIR)/RCS;\
+	fi; :
 
 # make archive will copy all the source stuff to a floppy archive.
 archive : unlisted exchange
 	cd $(BACKUPDIR); pax -wv . | freeze | vol -w /dev/fd0
 	if test -d $(BACKUPDIR)/RCS; then rm -rf $(BACKUPDIR)/RCS; fi; :
+	if test -d $(BACKUPDIR)/included; then rm -rf $(BACKUPDIR)/included; fi; :
 
 # make update should read an archive off of floppy into the BACKUPDIR
 # make update exchange should then exchange that info with the current
@@ -64,12 +98,11 @@ archlist :
 
 # make unlisted determines whether the macros for files to be saved
 # or purged define all the files in the directory.
-# add commands to recurse through subdirectories as necessary:
-#	@cd regress; $(MAKE) $(MAKEFLAGS) unlisted
-unlisted :
-	@echo Checking for unlisted files in ${PWD}/makefile:
-	@find . -level 1 -a -type f -a ! -name \*.TMP | sort >$(BACKUPDIR)files
-	@(for i in $(SAVE) $(PURGE); do echo ./$$i; done) | sort >$(BACKUPDIR)list
-	@diff $(BACKUPDIR)files $(BACKUPDIR)list | grep "^<" > $(BACKUPDIR)unlisted; :
-	@rm $(BACKUPDIR)files $(BACKUPDIR)list
-	@if test -s $(BACKUPDIR)unlisted; then cat $(BACKUPDIR)unlisted; rm $(BACKUPDIR)unlisted; false; else rm $(BACKUPDIR)unlisted; fi
+unlisted : Makefile
+	@echo Checking for unlisted files in $(PWD)/Makefile:
+	@find . -level 1 -a -type f -a ! -name \*.TMP | sort >$(ULRT)files
+	@(for i in $(SAVE) $(PURGE); do echo ./$$i; done) | sort >$(ULRT)list
+	@diff $(ULRT)files $(ULRT)list | grep "^<" > $(ULRT)unlisted; :
+	@rm $(ULRT)files $(ULRT)list
+	@if test -s $(ULRT)unlisted; then cat $(ULRT)unlisted; rm $(ULRT)unlisted; false; else rm $(ULRT)unlisted; fi
+	@$(RECURSE)
